##===================================================================##
 # SPDX-License-Identifier: GPL-3.0-or-later                         #
 # Copyright (c) 2025 Jimmy Källhagen                                #
 # Part of Yggdrasil - Nordix desktop environment                    #
 # Nordix and Yggdrasil are registered trademarks of Jimmy Källhagen # 
##===================================================================##

*    soft memlock 2097152    # 2GB (in KB)
*    hard memlock 4194304    # 4GB (in KB)

*    soft nofile 524288
*    hard nofile 524288

*    soft nproc 65536
*    hard nproc 131072

  @audio   soft rtprio 99
  @audio   hard rtprio 99
  @audio   soft nice -19
  @audio   hard nice -19
                         
                     @audio   soft memlock unlimited
                     @audio   hard memlock unlimited

                     @libvirt soft memlock unlimited
                     @libvirt hard memlock unlimited
                     @kvm     soft memlock unlimited
                     @kvm     hard memlock unlimited

  @wheel   soft rtprio 99
  @wheel   hard rtprio 99
  @wheel   soft nice -19
  @wheel   hard nice -19