#!/hint/bash
# shellcheck disable=2034

#
# /etc/makepkg.conf.d/rust.conf

# Nordix - Optimized Rust build configuration using native target tuning,
# Clang/LLD linker chain with cross-language LTO and ICF

#########################################################################
# RUST LANGUAGE SUPPORT
#########################################################################

# Flags used for the Rust compiler, similar in spirit to CFLAGS. Read
# linkman:rustc[1] for more details on the available flags.
#RUSTFLAGS="-C opt-level=3 -C target-cpu=native"

RUSTFLAGS="-C opt-level=3 -C target-cpu=native -C linker=clang -C linker-plugin-lto -C link-arg=-fuse-ld=lld -C link-arg=-Wl,--icf=safe"

# Additional compiler flags appended to `RUSTFLAGS` for use in debugging.
# Usually this would include: ``-C debuginfo=2''. Read linkman:rustc[1] for
# more details on the available flags.
DEBUG_RUSTFLAGS="-C debuginfo=2"
